name: Azure Az Login Test

on:
  workflow_dispatch:

# permissions:
#   id-token: write

jobs:
  login:
    runs-on: windows-latest
    steps:
    - run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
