name: Check Azure CLI
on:
  workflow_dispatch:      
jobs:
  azure-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az extension add --upgrade -n containerapp
            az containerapp --help
            az version
