name: Trigger auto deployment for containerapps-albumui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerapps-albumui-AutoDeployTrigger-37220393-fc76-4e86-9cda-d44ef0bd6316.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrhihorika.azurecr.io
          username: ${{ secrets.CONTAINERAPPSALBUMUI_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPSALBUMUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrhihorika.azurecr.io/containerapps-albumui:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPSALBUMUI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapps-albumui -g rg-album-demo --server acrhihorika.azurecr.io --username  ${{ secrets.CONTAINERAPPSALBUMUI_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPSALBUMUI_REGISTRY_PASSWORD }}
            az containerapp update -n containerapps-albumui -g rg-album-demo --image acrhihorika.azurecr.io/containerapps-albumui:${{ github.sha }}
