name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR: acrgithubactions.azurecr.io
  AZURE_CLIENT_ID: 22b51d87-6ce5-46f4-aa20-ae9e5074df71

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # Login to Azure
      # https://docs.microsoft.com/ja-jp/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux
      - uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: docker login, build and push
        run: |
          az acr login -n ${{ env.ACR }}
          # access_token=$(az account get-access-token --query accessToken -o tsv)
          # echo ${access_token}
          # refresh_token=$(curl https://${{ env.ACR }}/oauth2/exchange -s -d "grant_type=access_token&service=${{ env.ACR }}&access_token=$access_token&tenant=${{ secrets.AZURE_TENANT_ID }}" | jq -r .refresh_token)
          # echo ${refresh_token}
          # docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin  ${{ env.ACR }} <<< "$refresh_token"
          docker build . -t ${{ env.ACR }}/myhealth.web:latest
          docker push -a ${{ env.ACR }}/myhealth.web
        working-directory: ./src/MyHealth.Web
      # - name: "Login to ACR"
      #   id: getRefreshToken
      #   run: |
      #     az account show
      #     access_token=$(az account get-access-token --query accessToken -o tsv)
      #     echo $access_token
      #     curl https://${{ env.ACR }}/oauth2/exchange -s -d "grant_type=access_token&service=${{ env.ACR }}&access_token=$access_token&tenant=${{ secrets.AZURE_TENANT_ID }}"
      #     refresh_token=$(curl https://${{ env.ACR }}/oauth2/exchange -s -d "grant_type=access_token&service=${{ env.ACR }}&access_token=$access_token&tenant=${{ secrets.AZURE_TENANT_ID }}" | jq -r .refresh_token)
      #     echo $refresh_token
      #     # # The null GUID 0000... tells the container registry that this is an ACR refresh token during the login flow
      #     # # docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin  ${{ env.ACR }} <<< "$refresh_token"
      #     # echo "::set-output name=REFRESH_TOKEN::${refresh_token}"

      # - run: |
      #     echo ${{ steps.getRefreshToken.outputs.REFRESH_TOKEN }}
      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ env.ACR }}
      #     username: 00000000-0000-0000-0000-000000000000
      #     password: ${{ steps.getRefreshToken.outputs.REFRESH_TOKEN }}
