name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR: crdevopshandson.azurecr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Login to Azure
      # https://docs.microsoft.com/ja-jp/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: "Login to ACR"
        run: |
          set -euo pipefail
          # see https://cloudarchitected.com/2021/09/logging-into-acr-in-github-actions/
          # see https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token
          az account get-access-token --query accessToken -o tsv
          access_token=$(az account get-access-token --query accessToken -o tsv)
          curl https://${{ env.ACR }}/oauth2/exchange -s -d "grant_type=access_token&service=${{ env.ACR }}&access_token=$access_token" | jq -r .refresh_token
          refresh_token=$(curl https://${{ env.ACR }}/oauth2/exchange -s -d "grant_type=access_token&service=${{ env.ACR }}&access_token=$access_token" | jq -r .refresh_token)
          # The null GUID 0000... tells the container registry that this is an ACR refresh token during the login flow
          docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin  ${{ env.ACR }} <<< "$refresh_token"
