on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo start
      - run: |
          echo finished
        environment:
          name: TestEnv