on:
  workflow_dispatch

jobs:
  test1:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo start

  test2:
    needs: test1  
    environment:
      name: TestEnv
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo finished
