name: Azure Login Test

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  login:
    runs-on: windows-latest
    steps:
    - uses: azure/login@v1
      with:
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
